os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install .
script: python tests/travis.py
notifications:
  email:
    on_success: never
    on_failure: always
